version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bitnami/apache2/htdocs/nwallet/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

